# Site settings
title: jaketbouma
description: 'Big Data Scientist'
# url: 'http://127.0.0.1:4000'
url: 'https://jaketbouma.github.io/blog'
baseurl: '/blog/'
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'jaketbouma.github.io'

author:
  name: 'Jake Bouma'
  email: jake.t.bouma@gmail.com
  twitter_username: jaketbouma
  # facebook_username: jaketbouma
  github_username:  jaketbouma
  linkedin_username:  jaketbouma

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
